version: '3.1'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ans-webapp
    restart: always
    tty: true
    environment:
      SERVICE_NAME: ans-webapp
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ans-webserver
    restart: always
    tty: true
    ports:
      - "8008:80"
      - "4431:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.17
    container_name: ans-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ans
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  #adminer for db access
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      
#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local 

